[[redirects]]
  from = "/"
  to = "/ja/"
  status = 301
  force = true
  conditions = {Language = ["ja"]}

[[redirects]]
  from = "/"
  to = "/en/"
  force = true
  status = 301
  conditions = {Language = ["en"]}
